### ISSUE TITLE
Instant ocean get ready to make salt water

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/inst_ocean_ta_sal#3]
- [x] pre-soak/rinse barrel
- [x] graduated cylinder
- [x] balance
- [x] instant ocean
- [x] RO or DI water
- [ ] install new ro pressure tank
- [x] sharpie to mark water level
- [ ] characterize heater in tank with fluke
- [ ] circulation pump? 
- [x] calibrated salinity meter
- [x] shiny app/equation to estimate amount of initial salt

**Comment by pmcelhany** [comment]
@dmperez89 Nice to see some checked boxes!

**Comment by dmperez89** [comment]
@pmcelhany good idea to put some low-hanging fruit on there so we can still get the sense of accomplishment from some check marks :)

**Comment by pmcelhany** [comment]
@dmperez89 we should probably start these lists with something like "put on shoes".

**Comment by dmperez89** [comment]
@pmcelhany Did you say a shiny app already exists for estimating amount of initial salt?

**Comment by pmcelhany** [comment]
I'm not sure. How did you figure it out last year? We can discuss if a shiny app is useful - it is just a simple multiplication factor  if you are making a new batch of seawater from scratch.

**Comment by dmperez89** [comment]
We can use this site for adding salt and water to a tank of varying full-ness [https://www.hamzasreef.com/Contents/Calculators/DirectSaltCalculator.php](url)

**Comment by pmcelhany** [comment]
make io water for crab experiments
